In [ ]:
import pandas as pd 

df_15 = pd.read_csv("../data/raw/2017.csv")

df_15.head()

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715
3,Switzerland,4,7.494,7.561772,7.426227,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007,2.276716
4,Finland,5,7.469,7.527542,7.410458,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612,2.430182

Function to load and clean data

In [3]:
def load_and_clean(filepath,year): 
    df = pd.read_csv(filepath) 
    df.rename(columns={
        #2015-16 and all those who are common in all rows
        "Country" : "country",
        "Happiness Rank" : "happiness_rank",
        "Happiness Score" : "happiness_score",
        "Economy (GDP per Capita)" : "gdp_per_capita",
        "Family" : "social_support",
        "Health (Life Expectancy)" : "life_expectancy",
        "Freedom" : "freedom",
        "Trust (Government Corruption)" : "corruption",
        "Generosity" : "generosity",  
        #2017
        "Happiness.Rank" : "happiness_rank",
        "Happiness.Score" : "happiness_score",
        "Economy..GDP.per.Capita." : "gdp_per_capita",
        "Health..Life.Expectancy." : "life_expectancy",
        "Trust..Government.Corruption." : "corruption",

        #2018 and 2019
        "Country or region" : "country",
        "Overall rank" : "happiness_rank",
        "Score" : "happiness_score",
        "GDP per capita" : "gdp_per_capita",
        "Social support" : "social_support", 
        "Healthy life expectancy" : "life_expectancy",
        "Freedom to make life choices" : "freedom",
        "Perceptions of corruption" : "corruption",


        },inplace=True)
    
    
    df.drop(columns=["Standard Error","Dystopia Residual","Lower Confidence Interval","Region","Upper Confidence Interval"
                     ,"Whisker.high","Whisker.low","Dystopia.Residual"],inplace=True,errors="ignore")
    
    df["year"] = year
    return df 

load_and_clean("../data/raw/2016.csv",2016).head()

,country,happiness_rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,corruption,generosity,year
0,Denmark,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2016
1,Switzerland,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2016
2,Iceland,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2016
3,Norway,4,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2016
4,Finland,5,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2016

In [10]:
df = []
for i in range(2015,2020): 
    df.append(load_and_clean(f"../data/raw/{i}.csv",i))


df_all = pd.concat(df, ignore_index=True)
df_all.to_csv("../data/processed/merged.csv", index=False)

In [11]:
#checking new data set 


df_all.head(10)
df_all.info()
df_all.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 782 entries, 0 to 781
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   country          782 non-null    object
 1   happiness_rank   782 non-null    int64
 2   happiness_score  782 non-null    float64
 3   gdp_per_capita   782 non-null    float64
 4   social_support   782 non-null    float64
 5   life_expectancy  782 non-null    float64
 6   freedom          782 non-null    float64
 7   corruption       781 non-null    float64
 8   generosity       782 non-null    float64
 9   year             782 non-null    int64
dtypes: float64(7), int64(2), object(1)
memory usage: 61.2+ KB

,happiness_rank,happiness_score,gdp_per_capita,social_support,life_expectancy,freedom,corruption,generosity,year
count,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,781.000000,782.000000,782.000000
mean,78.698210,5.379018,0.916047,1.078392,0.612416,0.411091,0.125436,0.218576,2016.993606
std,45.182384,1.127456,0.407340,0.329548,0.248309,0.152880,0.105816,0.122321,1.417364
min,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2015.000000
25%,40.000000,4.509750,0.606500,0.869363,0.440183,0.309768,0.054000,0.130000,2016.000000
50%,79.000000,5.322000,0.982205,1.124735,0.647310,0.431000,0.091000,0.201982,2017.000000
75%,118.000000,6.189500,1.236187,1.327250,0.808000,0.531000,0.156030,0.278832,2018.000000
max,158.000000,7.769000,2.096000,1.644000,1.141000,0.724000,0.551910,0.838075,2019.000000